# Generated by Django 5.0.3 on 2024-04-10 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attribute_id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute', models.CharField(max_length=255)),
                ('sub_attribute', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('revision_date', models.DateField()),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.auditor')),
            ],
        ),
        migrations.CreateModel(
            name='finalAuditAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('Attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.attribute')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.auditsession')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AddField(
            model_name='finalauditattribute',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.site'),
        ),
        migrations.AddField(
            model_name='auditsession',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.site'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
