# Generated by Django 5.0.3 on 2024-04-25 02:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_attributes_discrepency_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discrepency_audit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audit_date', models.DateTimeField()),
                ('auditor_name', models.CharField(max_length=100)),
                ('discrepancy', models.JSONField()),
            ],
            options={
                'db_table': 'Discrepancy_audit',
                'managed': False,
            },
        ),
    ]
